/*
 Copyright Andrew Lyczak.  All rights reserved.  No HTML pages and/or Javascript may be reproduced without prior permission of the author. */
function Exponent(){this.name="Roots & Exponents";this.group=1;this.re=jX5(/^(EX[SLMN]?)?(a|b|c|n|[\d\+\-i]+|-?\d+\/\d+)([\^rl])(\-?\d+)(\D.*)?$/);this.qd=this.ca=null;this.s8l=["a","b","c","i"];this.ie6=J5&&!J57UP;this.bZ0=0<=Hx.toLowerCase().indexOf("firefox/1.0");var j=this.ie6||this.bZ0;this.info="Pulse OK o presione <span style='font-variant:small-caps'>enter</span> para finalizar la respuesta.";this.jyb="<div style='padding:1ex;'><input id='OK' type='button' value='OK' class='u82' onclick='exponent.v86();' /></div>";
this.aWv=function(b){return/^-?\d+\/\d+$/.test(b)};this.describe=function(b,c,a){var d,e=this.re.exec(b),g=this.exs(b);if(this.jqs(b))return this.jql(b).htm;var h=this.jqs(b);g?d=this.Dp4(b):a&&"^"==e[3]&&this.aWv(e[2])?d=this.aRX(e[2],e[4]):"r"==e[3]?d=this.y58(e[2],e[4]):"l"==e[3]?d=this.v80(e[2],e[4]):(d=/\D/.test(e[2])?"("+e[2]+")":e[2],d=d+"<sup>"+e[4]+"</sup>",e[5]&&"_"!=e[5].charAt(0)&&(d+="&nbsp;&#215;&nbsp;"+this.describe(e[5].substr(1),!0)));e=d.replace(/<\//g,"..").indexOf("/");g&&0<e&&
a&&(d="<div style='float:right;'><table cellpadding=0 cellspacing=0 style='margin-top:2px'><tr><td style='text-align:center'>"+d.substr(0,e)+"</td></tr><tr><td style='height:1px;'><div style='height:0px;border-top:1px solid black;font-size:0px;'></div></td></tr><tr><td style='text-align:center;'>"+d.substr(e+1).replace(/\(|\)/g,"")+"</td></tr></table></div>");c||(h?(b=b.split("_").pop(),d+=" = "+this.jqy(b)):d+=" = "+this.u6y(b));return d};this.exs=function(b){return"EXS"==b.substr(0,3)};this.jyy=
/^EX([LMN])([\w]+)\^(\-?\d+)([X|\/])([\w]+)\^(\-?\d+)_([\w]+)\^(\-?\d+)$/;this.jqs=function(b){return this.jyy.test(b)};this.jql=function(b,c){var a=b.match(this.jyy),d=function(a,b,d){return sops(a)+"<sup>"+(d&&!c?"<b>":"")+(d&&c?"n":sops(b))+(d&&!c?"</b>":"")+"</sup>"},e=a[1],g="X"==a[4]?uA7:q59,a={op:g,t0base:a[2],t0exp:a[3],t0term:d(a[2],a[3],"M"==e),t1base:a[5],t1exp:a[6],t1term:d(a[5],a[6],"N"==e),t2base:a[7],t2exp:a[8],t2term:d(a[7],a[8],"L"==e)};a.leftSideHtm=a.t0term+" "+g+" "+a.t1term;a.rightSideHtm=
a.t2term;a.htm=a.leftSideHtm+" = "+a.rightSideHtm;"L"==e&&(a.ca=a.t2exp);"M"==e&&(a.ca=a.t0exp);"N"==e&&(a.ca=a.t1exp);return a};this.vJ9=function(b,c){this.re.test(b)&&(b=this.describe(b),c=this.describe(c));var a=/^(\d+)<sup>\-?(\d+)<\/sup>/i,d=a.exec(b),a=a.exec(c);if(null!=d&&null!=a)return d[1]!=a[1]?parseInt(d[1])-parseInt(a[1]):parseInt(d[2])-parseInt(a[2]);a=/^<sup.*>(.*)<\/sup>.*<var.*>(\d\d*)<\/var>/i;d=a.exec(b);a=a.exec(c);if(null!=d&&null!=a){if(d[1]==a[1])return parseInt(d[2])-parseInt(a[2]);
if(l60(d[1])&&l60(a[1]))return parseInt(d[1])-parseInt(a[1])}a=/^log<sub>(\d+)<\/sub>(\d+)/i;d=a.exec(b);a=a.exec(c);return null!=d&&null!=a?d[1]!=a[1]?parseInt(d[1])-parseInt(a[1]):parseInt(d[2])-parseInt(a[2]):b<c?-1:b>c?1:0};this.aV7=function(b,c){return"log<sub>"+c+"</sub>"+b};this.v80=function(b,c){var a;return-1!=(a=b.indexOf("+"))?this.aV7(b.substr(0,a),c)+" + "+this.aV7(b.substr(a+1),c):-1!=(a=b.indexOf("-"))?this.aV7(b.substr(0,a),c)+" "+vq6+" "+this.aV7(b.substr(a+1),c):this.aV7(b,c)};this.aRX=
function(b,c){var a=b.split("/"),d=[];d.push("<table class='qq'><tbody style='font-size:200%;'><tr>");d.push("<td"," style='vertical-align:bottom;color:#393939;font-weight:normal;' rowspan=3 ",">(</td><td style='font-size:10%'>&nbsp;</td><td"," style='vertical-align:bottom;color:#393939;font-weight:normal;' rowspan=3 ",">)</td></tr>");d.push("<tr><td"," style='font-weight:bold;font-size:40%;white-space:nowrap;","vertical-align:bottom;' >",a[0],"</td>");d.push("<td "," style='font-weight:bold;font-size:40%;white-space:nowrap;",
"' >",c,"</sup></td></tr>");d.push("<tr><td"," style='font-weight:bold;font-size:40%;white-space:nowrap;","border-top:3px solid black;padding-top:3px;' >",a[1],"</td></tr></tbody></table>");return d.join("")};this.y58=function(b,c){var a="<sup class='radic'>X</sup>&#8730;<var class='radicand'>Y</var>";2==c&&(a=a.replace(/X/,"&#160;&#160;"));return a.replace(/X/,c).replace(/Y/,vY7(b))};this.g95=function(b,c){return String(b).concat(/[2-9]|\d\d+|\-/.test(c)?"<sup>"+c+"</sup>":"")};this.jqy=function(b){var c=
b.match(/^([a-z0-9]+)\^(\-?\d+)$/);return c?this.g95(c[0],c[1]):b};this.k63=function(b){for(var c=/([a-z])\^(\-?)(\d+)(\^\-?\d+)?/g,a,d,e={pos:[],neg:[],let:[]},g,h,f,i;a=c.exec(b);)i=a[4],d=a[1],h=parseInt(a[3]),f=i?parseInt(a[4].substr(1)):1,1==h&&1==f&&(i=!1),e.let.push(d),e[d]=(e[d]||0)+("-"==a[2]?-1:1)*h*f,g="-"==a[2]?"neg":"pos",i?(a=1==f?d+"<sup>"+h+"</sup>":"("+d+"<sup>"+h+"</sup>)<sup>"+f+"</sup>",a=[a]):a=nJ(parseInt(a[3]),d),e[g]=e[g].concat(a);e.let=v97(e.let);return e};this.Dp4=function(b){var b=
this.k63(b),c=b.pos.join("&#183;")||"1",a=b.neg.join("&#183;");1<b.neg.length&&(a="("+a+")");return b.neg.length?c+"/"+a:c};this.qE3=function(b){for(var c=this.k63(b),a=c.let,d=[],b=0;b<a.length;b++)c[a[b]]&&d.push([10-Math.abs(c[a[b]]),c[a[b]],a[b]]);d.sort();d=map(d,function(a){return this.g95(a[2],a[1])},this,[]);d.length||(d=[1]);return d.join("")};this.u6y=function(b){var c,a,d=this.re.exec(b),e=parseInt(d[2]),g=parseInt(d[4]),h,f=Math.pow;if(this.exs(b))a=this.qE3(b);else if(-1!=(c=b.indexOf("_")))a=
b.substr(c+1);else if("^"==d[3]&&2==(h=d[2].split("/")).length)h=zZ8.apply({},map(map(h,parseInt),f,{},[Math.abs(g)])),0>g&&(h.reverse(),0>h[1]&&(h[0]=-h[0],h[1]=-h[1])),a=h.join("/");else if("^"==d[3])b=f(e,g),a=0<=g?b:(0>b?"-":"")+"1/"+Math.abs(f(e,-g));else for(c=0;c<=e;c++)if(f(c,g)==e){a=c;break}return a};this.aVr=function(b){var c=s97(b);"C"==zE2(b).id&&(9==c||13==c)?n78("D"):13==c&&this.v86()};this.show=function(b){if(this.jqs(b))this.jqq(b);else{this.qd=this.describe(b,1);var c=this.describe(b,
1,1),a=this.Cv3=this.exs(b),d=this.ca=this.u6y(b),e=b.match(this.re),g=(d=(e=this.aWv(e[2])?e[2].split("/"):!1)||this.aWv(d))?"exponent.aVr(event)":"return(quiz.jq3(event))",h=Wd&&s9k?"60":"40",f;f="<table align='center'><tbody><tr><td class='qqsm' rowspan=2 style='font-size:25px;text-align:right;width:50%;white-space:nowrap;padding-right:4px;";d&&(f+="vertical-align:top;");d&&!e&&(f+="padding-top:10px;");f=f+("'><div style='float:right'>"+c+"</div></td>")+("<td "+(e?"style='vertical-align:bottom;width:3ex;text-align:center;' ":
"class='vam' style='width:3ex;text-align:center;'")+"><span class='qqsm'>=</span></td>");f=this.exs(b)?f+("<td class='vam'><span class='uni'><input type='text' id='C' style='padding:3px;width:120px;height:"+h+"px;font-size:24px;vertical-align:bottom;font-family:\"Lucida sans Unicode\"' maxlength=12 onkeypress='return(exponent.y73(event));' onkeyup='return(quiz.jq3(event));' ></input></span></td>"):f+("<td style='padding:4px 4px 2px;width:6ex;text-align:center;'><input class='qqsm' style='width:5ex;' id='C' type='text' onkeyup='exponent.u75(\"C\");' onkeypress='"+
g+"' onclick='clr(\"C\");' maxlength=5 /></td><td></td>");f+="</tr>";d&&(f+="<tr><td/><td style='padding:4px;width:6ex;border-top:3px solid black;text-align:center;'><input type='text' class='qqsm' style='width:5ex' id='D' onkeypress='exponent.aVr(event)' onkeyup='exponent.u75(\"D\");' maxlength=3 /></td></tr>");f+="</tbody></table>";f+=this.jyb;d&&(f="Resuelva en términos reducidos"+f);this.Bt4=a?this.y73:null;quiz.bbhtm(f);n78("C")}};this.jqq=function(b){var c=this.jql(b,!0),b=b.charAt(2),a=function(a,
b,c){return"<td class='jqo'>"+a+"</td><td class='jqp qqsm "+(c?"":"jqk")+"'>"+(c?"<input class='qqsm l74' id='C' type='text' onkeyup='exponent.u75(\"C\");' onkeypress='return(quiz.jq3(event))' onclick='clr(\"C\");' maxlength=3 />":b)+"</td>"},b="<table><tbody class='qq'><tr>"+a(c.t0base,c.t0exp,"M"==b)+"<td class='jqm'>"+c.op+"</td>"+a(c.t1base,c.t1exp,"N"==b)+"<td class='jqm'>=</td>"+a(c.t2base,c.t2exp,"L"==b)+"</tr></tbody></table>",b=b+this.jyb;quiz.bbhtm(b);this.ca=c.ca;this.qd=c.htm+" : n";n78("C")};
this.EH0=function(b){b=b.replace(/<\/?sup>/gi,"");if(j)return b;var c,a,d={"-":8315,"0":8304,1:185,2:178,3:179};for(a=4;9>=a;a++)d[String(a)]=8304+a;for(c in d)b=b.replace(jX5(c,"g"),sfcc(d[c]));return b};this.DQ0=function(b){this.show(b);var b=q9("C"),c=this.ca;b.blur();this.aWv(c)?quiz.Eb6(c.split("/")):b.value=this.Cv3?this.EH0(c):c};this.y73=function(b,c){if(j)return!0;var a=c||s97(b);q53&&(109==a||289==a||49<=a&&57>=a)&&estp(b);var d,e=q9("C");if(47>a&&45!=a)return 32!=a;if(112<=a&&123>=a||65<=
a&&67>=a||97<=a&&99>=a)return!0;if(48<=a&&57>=a&&b.shiftKey)return!1;if(45==a||109==a||189==a||48<=a&&57>=a){if(45==a||109==a||189==a)d=8315;48==a&&(d=8304);49==a&&(d=185);50==a&&(d=178);51==a&&(d=179);52<=a&&57>=a&&(d=8308+a-52);a=sfcc(d);if(!this.ie6&&e.createTextRange)estp(b),document.selection.createRange().duplicate().text=a;else if(!this.bZ0&&e.setSelectionRange){estp(b);d=e.selectionStart;var g=e.selectionEnd,h=e.value;e.value=h.substr(0,d).concat(a,h.substr(g));e.focus();g=d+a.length;e.setSelectionRange(g,
g)}else return!0}return!1};this.u75=function(b){var b=q9(b),c=b.value;c.length&&!/[i\-\d]$/i.test(c)?b.value=c.substr(0,c.length-1):quiz.begin()};this.nre=function(){return jX5("[a-z]\\-?\\d*","gi")};this.Bs9=function(b,c){for(var a=this.nre(),d=this.nre(),e=[],g=[],h;h=a.exec(b);)e.push(h[0]);for(;a=d.exec(c);)g.push(a[0]);e.sort();g.sort();return e.join("_")==g.join("_")};this.Fx1=function(b){var c,a=[],d={8315:"-",185:1,178:2,179:3,8304:"0",8308:4,8309:5,8310:6,8311:7,8312:8,8313:9},e=this.ca.replace(/<\/?sup>/gi,
"");for(c=0;c<b.length;c++)a.push(d[b.charCodeAt(c)]||b.charAt(c));a=a.join("").toLowerCase();this.Bs9(a,e)?quiz.k60():quiz.hJ3(this.qd+"="+this.ca,a.replace(/([\-\d]+)/g,"<sup>$1</sup>"))};this.v86=function(){var b=q9("C"),b=bJd(b.value.replace(/I/,"i")),c=this.ca;quiz.begin();if(this.Cv3)return this.Fx1(b);if(this.aWv(c)){var a=q9("D").value.replace(/\s/g,"");"-"==a.charAt(0)&&"-"!=b.charAt(0)&&(b="-"+b,a=a.substr(1));""==a&&(a="1");b=b+"/"+a}b==c?quiz.k60():quiz.hJ3(this.qd+"="+c,b)}}
aWy([".jqo {vertical-align:bottom;height:2em;}",".jqp {vertical-align:top;height:2em;}","input.l74 {width:3.5ex;}",".jqm {vertical-align:bottom;padding-right:10px}",".jqk {padding-top: 6px;}"]);document.s8f&&document.s8f("Exponent");
